# Kunskapskontroll 2 – Del 1, Modellera MNIST datan

### Använd maskininlärning för att modellera MNIST datan. Du skall utvärdera minst två olika modeller i ditt arbete och göra ett komplett ML-flöde, från början, där du laddar in data, till slut, där du utvärderar den bäst valda modellen på din test data.

### Jag använder två modeller: Logistic Regression och Random Forest.

In [15]:
# Importera nödvändiga bibliotek
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [17]:
# 1. Ladda in data
print("Laddar in MNIST-datan...")
data = fetch_openml("mnist_784", version=1)
X, y = data.data, data.target.astype(int)

Laddar in MNIST-datan...


In [19]:
# 2. Dela upp data i träning, validering och test
print("Delar upp data i träning, validering och test...")
X_train_full, X_test, y_train_full, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_train_full, y_train_full, test_size=0.25, random_state=42) # 60/20/20 split

Delar upp data i träning, validering och test...


In [21]:
# 3. Normalisera datan
print("Normaliserar data...")
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)

Normaliserar data...


In [23]:
# 4. Träna och utvärdera modeller
print("Tränar och utvärderar modeller...")

Tränar och utvärderar modeller...


In [27]:
# Modell 1: Logistic Regression
log_reg = LogisticRegression(max_iter=1000, solver='lbfgs', random_state=42)
log_reg.fit(X_train, y_train)
y_val_pred_logreg = log_reg.predict(X_val)
logreg_accuracy = accuracy_score(y_val, y_val_pred_logreg)
print(f"Logistic Regression Accuracy (Validering): {logreg_accuracy:.4f}")

Logistic Regression Accuracy (Validering): 0.9108


In [31]:
# Modell 2: Random Forest
rf_clf = RandomForestClassifier(n_estimators=100, random_state=42)
rf_clf.fit(X_train, y_train)
y_val_pred_rf = rf_clf.predict(X_val)
rf_accuracy = accuracy_score(y_val, y_val_pred_rf)
print(f"Random Forest Accuracy (Validering): {rf_accuracy:.4f}")

Random Forest Accuracy (Validering): 0.9652


In [29]:
# 5. Välj bästa modell och utvärdera på testdata
if logreg_accuracy > rf_accuracy:
    print("Logistic Regression valdes som den bästa modellen.")
    best_model = log_reg
else:
    print("Random Forest valdes som den bästa modellen.")
    best_model = rf_clf

Random Forest valdes som den bästa modellen.


In [34]:
# Utvärdera på testdata
print("Utvärderar den bästa modellen på testdatan...")
y_test_pred = best_model.predict(X_test)
test_accuracy = accuracy_score(y_test, y_test_pred)
print(f"Test Accuracy: {test_accuracy:.4f}")

Utvärderar den bästa modellen på testdatan...
Test Accuracy: 0.9646


In [36]:
# 6. Rapportera prestanda
print("\nClassification Report (Test Data):")
print(classification_report(y_test, y_test_pred))
print("\nConfusion Matrix (Test Data):")
print(confusion_matrix(y_test, y_test_pred))


Classification Report (Test Data):
              precision    recall  f1-score   support

           0       0.98      0.99      0.98      1343
           1       0.98      0.98      0.98      1600
           2       0.95      0.97      0.96      1380
           3       0.95      0.95      0.95      1433
           4       0.96      0.97      0.96      1295
           5       0.97      0.95      0.96      1273
           6       0.98      0.98      0.98      1396
           7       0.96      0.96      0.96      1503
           8       0.95      0.95      0.95      1357
           9       0.96      0.95      0.95      1420

    accuracy                           0.96     14000
   macro avg       0.96      0.96      0.96     14000
weighted avg       0.96      0.96      0.96     14000


Confusion Matrix (Test Data):
[[1323    0    3    0    2    2    3    1    8    1]
 [   0 1576    5    7    2    1    0    6    2    1]
 [   5    4 1332    5    4    1   10    8    8    3]
 [   1    0   2