# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [2]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [4]:
A = np.arange(1, 16).reshape(3,5)

In [6]:
"""
A.ndim: Print the number of axes (dimensions)
A.shape: Print the shape (dimensions in each axis)
A.size: Print the total number of elements
A.dtype: Print the data type of the elements
"""
A.ndim

2

In [8]:
A.shape

(3, 5)

In [10]:
A.size

15

In [12]:
A.dtype

dtype('int32')

### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [14]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [22]:
# Elementwise subtraction.
print(B-C)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]


In [24]:
# Elementwise multiplication.
print(B*C)

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


In [26]:
#Matrix multiplication (by default you should use the @ operator).
B@C

array([[12., 12., 12.],
       [30., 30., 30.],
       [48., 48., 48.]])

### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [32]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
# 1. Exponentiate each element
exp_each_element=(np.exp(B))
print("Exponentiate each element")
print (exp_each_element)
print()

# 2. Minimum value in whole matrix
min_total = np.min(B)
print("Minimum value in whole matrix")
print (min_total)
print()

# 3. Minimum value in each row
min_rows = np.min(B, axis=1)
print("Minimum value in each row")
print (exp_each_element)
print()

# 4. Minimum value in each column
min_cols = np.min(B, axis=0)
print("Minimum value in each column")
print (min_cols)
print()

# 5. Index of minimum value in whole matrix
min_index = np.argmin(B)
print("Index of minimum value in whole matrix")
print (min_index)
print()

# 6. Index of minimum value in each row
min_row_indices = np.argmin(B, axis=1)
print("Index of minimum value in each row")
print( min_row_indices)
print()

# 7. Sum of all elements
total_sum = np.sum(B)
print("Sum of all elements")
print (total_sum)
print()

# 8. Mean of each column
col_means = np.mean(B, axis=0)
print("Mean of each column")
print (col_means)
print()

# 9. Median of each column
col_medians = np.median(B, axis=0)
print("Median of each column")
print (col_medians)
print()

Exponentiate each element
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minimum value in whole matrix
1

Minimum value in each row
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minimum value in each column
[1 2 3]

Index of minimum value in whole matrix
0

Index of minimum value in each row
[0 0 0]

Sum of all elements
45

Mean of each column
[4. 5. 6.]

Median of each column
[4. 5. 6.]



### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [40]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [46]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [ ]:
# It returns the second row (if i input 0 instead of 1 that in returns the first row)

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [48]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [50]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [52]:
#Iterate elementwise
for element in A.flat:
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [54]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
b är tredimensionell, ett rätblock
2 lager
3 rader per lager
4 kolumner per rad

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [ ]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [ ]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

In [ ]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [56]:
def add_mult_matrices(matrix1, matrix2, operation):
    # Validate that inputs are numpy arrays
    if not (isinstance(matrix1, np.ndarray) and isinstance(matrix2, np.ndarray)):
        raise TypeError("Both matrices must be numpy arrays")
    
    # Validate operation argument
    if operation not in ['add', 'multiply']:
        raise ValueError("Operation must be either 'add' or 'multiply'")
    
    if operation == 'add':
        # Validate matrices have same size
        if matrix1.shape != matrix2.shape:
            raise ValueError("For addition, matrices must have the same shape")
        return matrix1 + matrix2
    
    else:  # operation == 'multiply'
        # Validate matrices can be multiplied
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError("For multiplication, number of columns in first matrix must equal number of rows in second matrix")
        return np.dot(matrix1, matrix2)

In [58]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [68]:
C=2*a
C

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [70]:
add_mult_matrices(a, C, "add")

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87])

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [ ]:
***
Uppgift 10.1.1. Definiera vektorn x enligt nedan.
x = (4, 3)
(a) Vilken dimension har vektorn x? SVAR=1x2
(b) Ber¨akna 5x. SVAR= (20,15)
(c) Ber¨akna 3x. SVAR= (12,9)
(d) Ber¨akna 5x + 3x. SVAR=(32,24)
(e) Ber¨akna 8x. SVAR=(32,24)
(f) Ber¨akna 4x − x. SVAR (12,9)
(g) Ber¨akna x
⊤, vilken blir den nya dimensionen efter att
transponeringen utf¨orts? 2x1
(h) Ar ¨ x + x
⊤ definierat? SVAR = Nej, vektorerna har olika dimension
(i) Ber¨akna ∥x∥. SVAR 16+9 =25 Roten ur 25 är 5 - SVAR 5


  
***

In [83]:
***
Uppgift 10.1.2. Definiera vektorn v enligt nedan.
v =
3
7
0
11

(a) Vilken dimension har vektorn v? SVAR 4x1
(b) Ber¨akna 2v.
SVAR=
6
13
0
22


(c) Ber¨akna 5v + 2v.
21
49
0
77


(d) Ber¨akna 4v − 2v.
6
14
0
22

(e) Ber¨akna v
⊤, vilken blir den nya dimensionen efter att
transponeringen utf¨orts?
1X4
(f) Ber¨akna ∥v∥.

    3 7 0 11 ,,, 9 49 0 121 = Roten ur 179
***
    

SyntaxError: invalid decimal literal (3765372809.py, line 9)

In [ ]:
***
Uppgift 10.1.3. Definiera vektorerna v1 = (4, 3, 1, 5) och
v2 = (2, 3, 1, 1).
(a) Ber¨akna ∥v1∥.
16 9 1 25 SVAR Roten ur 51



(b) Ber¨akna ∥v1 − v2∥.  

v1-v2 = 2,0,0,4
Roten ur 4 + 16 =Roten ur 20

***

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [ ]:
Ovningsuppgifter ¨
Uppgift 10.2.1. Definiera matriserna
A =

2 1 −1
1 −1 1 
, B =

4 −2 1
2 −4 −2

, C =

1 2
2 1
,
D =

3 4
4 3
, E =

1
2

. I =

1 0
0 1
.
Om det ¨ar definierat, utf¨or f¨oljande ber¨akningar:
(a) 2A
4,2,-2
2,-2,2

(b) B − 2A
4,-2,1   4,2,-2  0,-4,3
2,-4,-2  2,-2,2  0,-2,-4

(c) 3C − 2E
, C =

1 2
2 1
, E =

1
2

Ej definierat - olika dimensioner
    
(d) 2D − 3C
D =

3 4
4 3
 C =

1 2
2 1

6 8     3 6     3 2
8 6     6 3     2 3


(e) D⊤ + 2D
D =

3 4
4 3

9 12
12 9

(f) 2C⊤ − 2D⊤
2 4   6 8   -4 -4
4 2   8 6   -4 -4


(g) A⊤ − B
Ej definierat

(h) AC
Ej definierat

(i) CD
C =

1 2
2 1
,
D =

3 4
4 3

1x3+2x4 1x4+2x3
2x3+1x4 2x4 1x3

11 10
10 11

(j) CB


(k) CI
1 2
2 1

(l) AB⊤
5 2
7 4

In [ ]:
Uppgift 10.2.2. Definiera matrisen
A =

2 3 4
5 4 1
Ber¨akna AAT
.


In [ ]:
Uppgift 10.2.3. Definiera matriserna
A =

1 2
2 4
, B =

2 1
1 3
och C =

4 3
0 2
.
Verifiera att AB = AC men att B ̸= C. Vad vi vill demonstrera med detta exemplet ¨ar att vi har definierat ett nytt
matematiskt objekt (matriser i detta fallet) och att de ”vanliga reglerna” f¨or aritmetik som vi l¨art oss fr˚an grundskolan
inte n¨odv¨andigtvis g¨aller ¨aven h¨ar.
    


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [72]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [74]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [76]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)


[  0   1   2 123]
[  2 123]
